#ifndef _FLAGS_H_
#define _FLAGS_H_
#define SIGN_IN 1
#define SIGN_IN_SUCCESS 2
#define SIGN_IN_FAIL  3
#define SIGN_UP 4
#define SIGN_UP_SUCCESS 5
#define SIGN_UP_FAIL 6
#define LOG_OUT 7
#define LOG_OUT_ACK 8
#define SERVER_ERROR 9
#define GET_ALL_CLIENT 10
#define ALL_CLIENT_ACK 11
#define GET_ONLINE_CLIENT 12
#define ONLINE_CLIENT_ACK 13
#define GET_CLIENT_PET 14
#define CLIENT_PET_ACK 15
#define SET_PET_NAME 16
#define SET_PET_NAME_SUCCESS 17
#define SET_PET_NAME_FAIL 18
#define UPDATE_PET 19
#define UPDATE_PET_SUCCESS 20
#define UPDATE_PET_FAIL 21
#define UPDATE_CLIENT 22
#define UPDATE_CLIENT_SUCCESS 23
#define UPDATE_CLIENT_FAIL 24
#define GET_ONE_MORE_POKEMON 25
#define GET_ONE_MORE_POKEMON_SUCCESS 26
#define GET_ONE_MORE_POKEMON_FAIL 27
#endif
